### ISSUE TITLE
Also an easy way to be grabbed thanks

### ISSUE THREAD

**Issue by HideakiAtsuyo** [DiscordFucker/QRCode-Grabber#1]
https://github.com/DiscordFucker/QRCode-Grabber/blob/a0b364527e600a7aba4a8b5456d43d4eba3aba2b/index.html#L40

**Comment by Stanley-GF** [comment]
stfu, deobfuscate the code or go in network u gonna c 0 web request.

**Comment by Stanley-GF** [comment]
useless issue, closd

**Comment by HideakiAtsuyo** [comment]
Effectivement c'est sur votre site à vous le grabber ;)

**Comment by RealAlphabet** [comment]
> Effectivement c'est sur votre site à vous le grabber ;)

Tu as lu le titre du repo au moins ?
